"""add sale_items and sale_expenses

Revision ID: 209d95ad272e
Revises: 5344a21ccb55
Create Date: 2026-09-20 08:47:07.019777

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '209d95ad272e'
down_revision: Union[str, Sequence[str], None] = '5344a21ccb55'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sale_expenses', sa.Column('item_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'sale_expenses', 'sale_items', ['sale_id', 'item_id'], ['sale_id', 'item_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'sale_expenses', type_='foreignkey')
    op.drop_column('sale_expenses', 'item_id')
    # ### end Alembic commands ###
