"""Initial schema

Revision ID: bda1fa73fba3
Revises: 
Create Date: 2026-09-09 19:52:08.387481

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bda1fa73fba3'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('purchases',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source', sa.String(), nullable=True),
    sa.Column('purchased_date', sa.Date(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('price', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('purchase_id', sa.Integer(), nullable=False),
    sa.Column('parent_item_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['parent_item_id'], ['items.id'], ),
    sa.ForeignKeyConstraint(['purchase_id'], ['purchases.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sales',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('kind', sa.String(length=4), server_default='sale', nullable=False),
    sa.Column('sold_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("kind IN ('sale', 'loss')", name='sale_kind_valid'),
    sa.CheckConstraint('price >= 0', name='sale_price_nonnegative'),
    sa.ForeignKeyConstraint(['item_id'], ['items.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sales_item_id'), 'sales', ['item_id'], unique=False)
    op.create_table('refunds',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sale_id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('refunded_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('amount > 0', name='refund_amount_positive'),
    sa.ForeignKeyConstraint(['sale_id'], ['sales.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_refunds_sale_id'), 'refunds', ['sale_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_refunds_sale_id'), table_name='refunds')
    op.drop_table('refunds')
    op.drop_index(op.f('ix_sales_item_id'), table_name='sales')
    op.drop_table('sales')
    op.drop_table('items')
    op.drop_table('purchases')
    # ### end Alembic commands ###
